### ISSUE TITLE
How to soft delete?

### ISSUE THREAD

**Issue by denielaa** [esbenp/genie#1]
Hi @esbenp 
good to found this repo and, currently I am using it. and great article about modern REST API. 

I have checked the source code, but there is no soft delete currently. Or did I miss it?

**Comment by od3n** [comment]
@denielaa have you enable soft deletes?

[Soft Deleting](https://laravel.com/docs/5.4/eloquent#soft-deleting)

To enable soft deletes for a model, use the  Illuminate\Database\Eloquent\SoftDeletes trait on the model and add the deleted_at column to your $dates property:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Flight extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
}
```

**Comment by denielaa** [comment]
oh, so the implementation is still the same. 
I thought it will be handled by genie.

**Comment by denielaa** [comment]
so the implementation still the same. 
I thought it will be in genie.
I will close this issue, thanks
